# Generated by Django 5.0.4 on 2024-04-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_number', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('score_a', models.IntegerField()),
                ('score_b', models.IntegerField()),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_a', to='myapp.user')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_b', to='myapp.user')),
            ],
        ),
    ]
